# Generated by Django 2.2 on 2020-07-06 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custID', models.IntegerField()),
                ('site', models.TextField(blank=True)),
                ('createdBy', models.CharField(max_length=50)),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 6, 9, 31, 40, 980191))),
            ],
            options={
                'db_table': 'user_site',
            },
        ),
    ]
