# Generated by Django 4.0.5 on 2022-07-28 22:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='betaTesters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250)),
                ('security_code', models.CharField(max_length=250)),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 591329), null=True)),
            ],
            options={
                'db_table': 'beta_testers',
            },
        ),
        migrations.CreateModel(
            name='ssFAQs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('short_description', models.TextField()),
                ('url', models.CharField(max_length=250)),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 589889), null=True)),
                ('updatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 589911), null=True)),
            ],
            options={
                'db_table': 'ss_faq',
            },
        ),
        migrations.CreateModel(
            name='ssLatestOffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('shortDescription', models.CharField(max_length=250)),
                ('startDate', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 588150), null=True)),
                ('endDate', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 588169), null=True)),
                ('isActive', models.IntegerField(blank=True, default=0)),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 588193), null=True)),
                ('updatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 588207), null=True)),
            ],
            options={
                'db_table': 'ss_latest_offers',
            },
        ),
        migrations.CreateModel(
            name='ssPromoCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=250)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('discount_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.IntegerField(blank=True, default=0)),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 590337), null=True)),
                ('updatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 590382), null=True)),
            ],
            options={
                'db_table': 'ss_promo_codes',
            },
        ),
        migrations.CreateModel(
            name='ssRoadmapReleases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('updateType', models.CharField(max_length=250)),
                ('releaseDate', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 588824), null=True)),
                ('isActive', models.IntegerField(blank=True, default=0)),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 588855), null=True)),
                ('updatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 588870), null=True)),
            ],
            options={
                'db_table': 'ss_roadmap_releases',
            },
        ),
        migrations.CreateModel(
            name='ssWebsiteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=250)),
                ('is_active', models.IntegerField(default=1)),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 580548), null=True)),
                ('updatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 580567), null=True)),
            ],
            options={
                'db_table': 'ss_website_type',
            },
        ),
        migrations.CreateModel(
            name='userDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=250)),
                ('domain_id', models.IntegerField(blank=True, default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('server_ip', models.CharField(blank=True, max_length=250)),
                ('auto_renew', models.IntegerField(blank=True, default=0)),
                ('is_active', models.IntegerField(blank=True, default=1)),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 584066), null=True)),
                ('updatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 584083), null=True)),
            ],
            options={
                'db_table': 'user_domain',
            },
        ),
        migrations.AlterField(
            model_name='sstemplates',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 580058), null=True),
        ),
        migrations.AlterField(
            model_name='sstemplates',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 580081), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 577586), null=True),
        ),
        migrations.CreateModel(
            name='userSites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='null', max_length=250)),
                ('is_active', models.IntegerField(blank=True, default=0)),
                ('is_published', models.IntegerField(blank=True, default=0)),
                ('is_domain_connected', models.IntegerField(blank=True, default=0)),
                ('json_path', models.CharField(blank=True, default='', max_length=250)),
                ('folder_path', models.CharField(blank=True, default='', max_length=250)),
                ('site_website_type_id', models.IntegerField(blank=True, default=0)),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 581965), null=True)),
                ('updatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 581982), null=True)),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('domain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='siteApp.userdomain')),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='siteApp.sstemplates')),
            ],
            options={
                'db_table': 'user_sites',
            },
        ),
        migrations.CreateModel(
            name='userSeoSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robots_txt', models.CharField(max_length=250)),
                ('sitemap', models.CharField(max_length=250)),
                ('sitemap_xml', models.CharField(max_length=250)),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 585937), null=True)),
                ('updatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 585956), null=True)),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='siteApp.usersites')),
            ],
            options={
                'db_table': 'user_seo_settings',
            },
        ),
        migrations.CreateModel(
            name='userPurchasedTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(blank=True, max_length=250)),
                ('purchased_on', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 590804), null=True)),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='siteApp.sstemplates')),
            ],
            options={
                'db_table': 'user_purchased_templates',
            },
        ),
        migrations.CreateModel(
            name='userPaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(blank=True, default='', max_length=50)),
                ('last4', models.CharField(max_length=4)),
                ('exp_month', models.CharField(max_length=2)),
                ('exp_year', models.CharField(max_length=4)),
                ('brand', models.CharField(default='Visa', max_length=20)),
                ('is_default', models.IntegerField(default=1)),
                ('is_active', models.IntegerField(default=1)),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 581421), null=True)),
                ('updatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 581438), null=True)),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_payment_method',
            },
        ),
        migrations.CreateModel(
            name='userGeneralSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='null', max_length=250)),
                ('favicon', models.ImageField(default='default-favicon.png', upload_to='fav_icons')),
                ('siteseed_branding', models.IntegerField(blank=True, default=1)),
                ('sub_domain', models.CharField(default='null', max_length=250)),
                ('custom_domain', models.CharField(default='null', max_length=250)),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 585219), null=True)),
                ('updatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 585237), null=True)),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='siteApp.usersites')),
            ],
            options={
                'db_table': 'user_general_settings',
            },
        ),
        migrations.CreateModel(
            name='userFormsSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=250)),
                ('submition_to_address', models.CharField(max_length=250)),
                ('subject_line', models.CharField(max_length=250)),
                ('reply_address', models.CharField(max_length=250)),
                ('form_submission_count', models.CharField(max_length=250)),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 586509), null=True)),
                ('updatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 586527), null=True)),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteApp.usersites')),
            ],
            options={
                'db_table': 'user_forms_settings',
            },
        ),
        migrations.CreateModel(
            name='userFontsSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_fonts', models.CharField(max_length=250)),
                ('adobe_fonts_key', models.CharField(max_length=250)),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 587060), null=True)),
                ('updatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 587079), null=True)),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteApp.usersites')),
            ],
            options={
                'db_table': 'user_fonts_settings',
            },
        ),
        migrations.CreateModel(
            name='userExports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=250)),
                ('platform', models.CharField(max_length=250)),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 589302), null=True)),
                ('updatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 589321), null=True)),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='siteApp.usersites')),
            ],
            options={
                'db_table': 'user_exports',
            },
        ),
        migrations.CreateModel(
            name='userDomainHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_ip', models.CharField(max_length=250)),
                ('path', models.CharField(max_length=250)),
                ('conf_settings', models.CharField(max_length=250)),
                ('is_active', models.CharField(max_length=250)),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 584615), null=True)),
                ('updatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 584634), null=True)),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('domain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='siteApp.userdomain')),
            ],
            options={
                'db_table': 'user_domain_host',
            },
        ),
        migrations.AddField(
            model_name='userdomain',
            name='cust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='userBillingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=250)),
                ('address_line_2', models.CharField(max_length=250)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('zipcode', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=250)),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 582661), null=True)),
                ('updatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 582679), null=True)),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='siteApp.userpaymentmethod')),
            ],
            options={
                'db_table': 'user_billing_address',
            },
        ),
        migrations.CreateModel(
            name='userBackupSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_path', models.CharField(max_length=250)),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 587565), null=True)),
                ('updatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 587588), null=True)),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='siteApp.usersites')),
            ],
            options={
                'db_table': 'user_backup_settings',
            },
        ),
        migrations.CreateModel(
            name='ssStripeCustomers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(blank=True, max_length=250, null=True)),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 580909), null=True)),
                ('updatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 580929), null=True)),
                ('cust', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ss_stripe_customers',
            },
        ),
        migrations.CreateModel(
            name='paymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.CharField(blank=True, max_length=250, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('promo_code', models.CharField(blank=True, max_length=150, null=True)),
                ('subscription_id', models.CharField(blank=True, max_length=250, null=True)),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 583399), null=True)),
                ('updatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 22, 0, 27, 583416), null=True)),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteApp.userpaymentmethod')),
            ],
            options={
                'db_table': 'payment_history',
            },
        ),
    ]
