# Generated by Django 4.0.5 on 2022-07-29 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0002_betatesters_ssfaqs_sslatestoffers_sspromocodes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='zohoAuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, max_length=250)),
                ('refresh_token', models.CharField(blank=True, max_length=250)),
                ('api_domain', models.CharField(blank=True, max_length=100)),
                ('token_type', models.CharField(blank=True, max_length=50)),
                ('expires_in', models.IntegerField(blank=True, default=0)),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 836783), null=True)),
                ('updatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 836800), null=True)),
            ],
            options={
                'db_table': 'zoho_auth_token',
            },
        ),
        migrations.AlterField(
            model_name='betatesters',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 838137), null=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 829905), null=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 829923), null=True),
        ),
        migrations.AlterField(
            model_name='ssfaqs',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 836348), null=True),
        ),
        migrations.AlterField(
            model_name='ssfaqs',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 836366), null=True),
        ),
        migrations.AlterField(
            model_name='sslatestoffers',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 834845), null=True),
        ),
        migrations.AlterField(
            model_name='sslatestoffers',
            name='endDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 834819), null=True),
        ),
        migrations.AlterField(
            model_name='sslatestoffers',
            name='startDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 834801), null=True),
        ),
        migrations.AlterField(
            model_name='sslatestoffers',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 834859), null=True),
        ),
        migrations.AlterField(
            model_name='sspromocodes',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 837226), null=True),
        ),
        migrations.AlterField(
            model_name='sspromocodes',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 837242), null=True),
        ),
        migrations.AlterField(
            model_name='ssroadmapreleases',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 835310), null=True),
        ),
        migrations.AlterField(
            model_name='ssroadmapreleases',
            name='releaseDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 835283), null=True),
        ),
        migrations.AlterField(
            model_name='ssroadmapreleases',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 835324), null=True),
        ),
        migrations.AlterField(
            model_name='ssstripecustomers',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 827320), null=True),
        ),
        migrations.AlterField(
            model_name='ssstripecustomers',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 827339), null=True),
        ),
        migrations.AlterField(
            model_name='sstemplates',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 826483), null=True),
        ),
        migrations.AlterField(
            model_name='sstemplates',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 826505), null=True),
        ),
        migrations.AlterField(
            model_name='sswebsitetype',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 826957), null=True),
        ),
        migrations.AlterField(
            model_name='sswebsitetype',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 826980), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 823954), null=True),
        ),
        migrations.AlterField(
            model_name='userbackupsettings',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 834256), null=True),
        ),
        migrations.AlterField(
            model_name='userbackupsettings',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 834276), null=True),
        ),
        migrations.AlterField(
            model_name='userbillingaddress',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 829240), null=True),
        ),
        migrations.AlterField(
            model_name='userbillingaddress',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 829258), null=True),
        ),
        migrations.AlterField(
            model_name='userdomain',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 830641), null=True),
        ),
        migrations.AlterField(
            model_name='userdomain',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 830661), null=True),
        ),
        migrations.AlterField(
            model_name='userdomainhost',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 831200), null=True),
        ),
        migrations.AlterField(
            model_name='userdomainhost',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 831218), null=True),
        ),
        migrations.AlterField(
            model_name='userexports',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 835794), null=True),
        ),
        migrations.AlterField(
            model_name='userexports',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 835812), null=True),
        ),
        migrations.AlterField(
            model_name='userfontssettings',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 833730), null=True),
        ),
        migrations.AlterField(
            model_name='userfontssettings',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 833748), null=True),
        ),
        migrations.AlterField(
            model_name='userformssettings',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 833167), null=True),
        ),
        migrations.AlterField(
            model_name='userformssettings',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 833185), null=True),
        ),
        migrations.AlterField(
            model_name='usergeneralsettings',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 831796), null=True),
        ),
        migrations.AlterField(
            model_name='usergeneralsettings',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 831813), null=True),
        ),
        migrations.AlterField(
            model_name='userpaymentmethod',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 827958), null=True),
        ),
        migrations.AlterField(
            model_name='userpaymentmethod',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 827976), null=True),
        ),
        migrations.AlterField(
            model_name='userpurchasedtemplates',
            name='purchased_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 837629), null=True),
        ),
        migrations.AlterField(
            model_name='userseosettings',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 832434), null=True),
        ),
        migrations.AlterField(
            model_name='userseosettings',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 832452), null=True),
        ),
        migrations.AlterField(
            model_name='usersites',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 828525), null=True),
        ),
        migrations.AlterField(
            model_name='usersites',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 12, 1, 12, 828542), null=True),
        ),
    ]
