# Generated by Django 2.2 on 2020-07-13 02:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0002_auto_20200713_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='custhostingdetails',
            name='virtualConf',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='custdomaindetails',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 13, 2, 3, 56, 679305)),
        ),
        migrations.AlterField(
            model_name='custdomaindetails',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 13, 2, 3, 56, 679353)),
        ),
        migrations.AlterField(
            model_name='custhostingdetails',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 13, 2, 3, 56, 678442)),
        ),
        migrations.AlterField(
            model_name='custhostingdetails',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 13, 2, 3, 56, 678487)),
        ),
        migrations.AlterField(
            model_name='custhostingdomains',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 13, 2, 3, 56, 677567)),
        ),
        migrations.AlterField(
            model_name='custhostingdomains',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 13, 2, 3, 56, 677613)),
        ),
        migrations.AlterField(
            model_name='custmaster',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 13, 2, 3, 56, 674271)),
        ),
        migrations.AlterField(
            model_name='custmaster',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 13, 2, 3, 56, 674327)),
        ),
        migrations.AlterField(
            model_name='custservice',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 13, 2, 3, 56, 676076)),
        ),
        migrations.AlterField(
            model_name='custservice',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 13, 2, 3, 56, 676127)),
        ),
        migrations.AlterField(
            model_name='custstaticsite',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 13, 2, 3, 56, 680788)),
        ),
        migrations.AlterField(
            model_name='custstaticsite',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 13, 2, 3, 56, 680834)),
        ),
        migrations.AlterField(
            model_name='custwptheme',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 13, 2, 3, 56, 681626)),
        ),
        migrations.AlterField(
            model_name='custwptheme',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 13, 2, 3, 56, 681672)),
        ),
        migrations.AlterField(
            model_name='location',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 13, 2, 3, 56, 675171)),
        ),
        migrations.AlterField(
            model_name='location',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 13, 2, 3, 56, 675262)),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 13, 2, 3, 56, 683239)),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 13, 2, 3, 56, 683313)),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 13, 2, 3, 56, 682411)),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 13, 2, 3, 56, 682460)),
        ),
        migrations.AlterField(
            model_name='ssservicetype',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 13, 2, 3, 56, 676878)),
        ),
        migrations.AlterField(
            model_name='ssservicetype',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 13, 2, 3, 56, 676927)),
        ),
        migrations.AlterField(
            model_name='sstemplates',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 13, 2, 3, 56, 680070)),
        ),
        migrations.AlterField(
            model_name='sstemplates',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 13, 2, 3, 56, 680116)),
        ),
    ]
