# Generated by Django 2.1 on 2021-01-11 05:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0003_auto_20200713_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='notificationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.IntegerField()),
                ('notification_name', models.CharField(max_length=250)),
                ('is_active', models.CharField(max_length=250)),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 789946))),
                ('updatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 790028))),
            ],
            options={
                'db_table': 'notification_settings',
            },
        ),
        migrations.CreateModel(
            name='orderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.IntegerField()),
                ('order_master_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=250)),
                ('footer', models.CharField(max_length=250)),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 789054))),
                ('updatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 789085))),
            ],
            options={
                'db_table': 'order_detail',
            },
        ),
        migrations.CreateModel(
            name='ssLatestOffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('shortDescription', models.CharField(max_length=250)),
                ('startDate', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 798287))),
                ('endDate', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 798318))),
                ('isActive', models.IntegerField()),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 798352))),
                ('updatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 798375))),
            ],
            options={
                'db_table': 'ss_latest_offers',
            },
        ),
        migrations.CreateModel(
            name='ssRoadmapReleases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('updateType', models.CharField(max_length=250)),
                ('releaseDate', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 799187))),
                ('isActive', models.IntegerField()),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 799232))),
                ('updatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 799269))),
            ],
            options={
                'db_table': 'ss_roadmap_releases',
            },
        ),
        migrations.CreateModel(
            name='ssSubscriptionPlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=250)),
                ('plan_type', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=250)),
                ('validity', models.CharField(max_length=250)),
                ('is_active', models.CharField(max_length=250)),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 783033))),
                ('updatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 783062))),
            ],
            options={
                'db_table': 'ss_subscription_plans',
            },
        ),
        migrations.CreateModel(
            name='ssSubscriptionPlansDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ss_subscription_plans_id', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('is_active', models.IntegerField()),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 786156))),
                ('updatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 786186))),
            ],
            options={
                'db_table': 'ss_subscription_plans_details',
            },
        ),
        migrations.CreateModel(
            name='ssWebsiteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=250)),
                ('is_active', models.CharField(max_length=250)),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 782346))),
                ('updatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 782378))),
            ],
            options={
                'db_table': 'ss_website_type',
            },
        ),
        migrations.CreateModel(
            name='userBackupSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.IntegerField()),
                ('backup_path', models.CharField(max_length=250)),
                ('backup_date', models.CharField(max_length=250)),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 797572))),
                ('updatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 797602))),
            ],
            options={
                'db_table': 'user_backup_settings',
            },
        ),
        migrations.CreateModel(
            name='userBillingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.IntegerField()),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('zipcode', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 786886))),
                ('updatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 786915))),
            ],
            options={
                'db_table': 'user_billing_address',
            },
        ),
        migrations.CreateModel(
            name='userDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.IntegerField()),
                ('domain_name', models.CharField(max_length=250)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('server_ip', models.CharField(max_length=250)),
                ('is_active', models.CharField(max_length=250)),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 791132))),
                ('updatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 791167))),
            ],
            options={
                'db_table': 'user_domain',
            },
        ),
        migrations.CreateModel(
            name='userDomainHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.IntegerField()),
                ('domain_id', models.IntegerField()),
                ('server_ip', models.CharField(max_length=250)),
                ('path', models.CharField(max_length=250)),
                ('conf_settings', models.CharField(max_length=250)),
                ('is_active', models.CharField(max_length=250)),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 792176))),
                ('updatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 792228))),
            ],
            options={
                'db_table': 'user_domain_host',
            },
        ),
        migrations.CreateModel(
            name='userFontsSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.IntegerField()),
                ('custom_fonts', models.CharField(max_length=250)),
                ('adobe_fonts_key', models.CharField(max_length=250)),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 796879))),
                ('updatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 796915))),
            ],
            options={
                'db_table': 'user_fonts_settings',
            },
        ),
        migrations.CreateModel(
            name='userFormsSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.IntegerField()),
                ('form_name', models.CharField(max_length=250)),
                ('submition_to_address', models.CharField(max_length=250)),
                ('subject_line', models.CharField(max_length=250)),
                ('reply_address', models.CharField(max_length=250)),
                ('form_submission_count', models.CharField(max_length=250)),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 796168))),
                ('updatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 796213))),
            ],
            options={
                'db_table': 'user_forms_settings',
            },
        ),
        migrations.CreateModel(
            name='userGeneralSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.IntegerField()),
                ('favicon', models.CharField(max_length=250)),
                ('siteseed_branding', models.CharField(max_length=250)),
                ('custom_domain', models.CharField(max_length=250)),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 792933))),
                ('updatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 792962))),
            ],
            options={
                'db_table': 'user_general_settings',
            },
        ),
        migrations.CreateModel(
            name='userPaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.IntegerField()),
                ('stripe_id', models.IntegerField()),
                ('last4', models.CharField(max_length=4)),
                ('exp_month', models.CharField(max_length=2)),
                ('exp_year', models.CharField(max_length=4)),
                ('is_default', models.IntegerField(default=1)),
                ('is_active', models.IntegerField(default=1)),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 783972))),
                ('updatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 784002))),
            ],
            options={
                'db_table': 'user_payment_method',
            },
        ),
        migrations.CreateModel(
            name='userSeoSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.IntegerField()),
                ('robots_txt', models.CharField(max_length=250)),
                ('sitemap', models.CharField(max_length=250)),
                ('sitemap_xml', models.CharField(max_length=250)),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 795337))),
                ('updatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 795398))),
            ],
            options={
                'db_table': 'user_seo_settings',
            },
        ),
        migrations.CreateModel(
            name='userSites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.IntegerField()),
                ('template_id', models.IntegerField()),
                ('is_active', models.CharField(max_length=250)),
                ('path', models.CharField(max_length=250)),
                ('site_website_type_id', models.IntegerField()),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 784699))),
                ('updatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 784736))),
            ],
            options={
                'db_table': 'user_sites',
            },
        ),
        migrations.CreateModel(
            name='userSitesPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.IntegerField()),
                ('subscription_plan_id', models.IntegerField()),
                ('user_site_id', models.IntegerField()),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('is_active', models.IntegerField()),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 785406))),
                ('updatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 785433))),
            ],
            options={
                'db_table': 'user_site_plan',
            },
        ),
        migrations.DeleteModel(
            name='custDomainDetails',
        ),
        migrations.DeleteModel(
            name='custHostingDetails',
        ),
        migrations.DeleteModel(
            name='custHostingDomains',
        ),
        migrations.DeleteModel(
            name='custService',
        ),
        migrations.DeleteModel(
            name='custStaticSite',
        ),
        migrations.DeleteModel(
            name='custWpTheme',
        ),
        migrations.DeleteModel(
            name='location',
        ),
        migrations.DeleteModel(
            name='paymentMethod',
        ),
        migrations.DeleteModel(
            name='ssServiceType',
        ),
        migrations.RenameField(
            model_name='custmaster',
            old_name='custID',
            new_name='cust_id',
        ),
        migrations.RenameField(
            model_name='custmaster',
            old_name='firstName',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='custmaster',
            old_name='forgotpswdStatus',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='custmaster',
            old_name='lastName',
            new_name='forgot_pswd_status',
        ),
        migrations.RenameField(
            model_name='ordermaster',
            old_name='chargeID',
            new_name='cust_id',
        ),
        migrations.RenameField(
            model_name='ordermaster',
            old_name='description',
            new_name='path',
        ),
        migrations.RenameField(
            model_name='ordermaster',
            old_name='orderName',
            new_name='total_price',
        ),
        migrations.RenameField(
            model_name='sstemplates',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='sstemplates',
            old_name='templateName',
            new_name='path',
        ),
        migrations.RenameField(
            model_name='sstemplates',
            old_name='templatePrice',
            new_name='template_name',
        ),
        migrations.RemoveField(
            model_name='custmaster',
            name='createdBy',
        ),
        migrations.RemoveField(
            model_name='custmaster',
            name='updatedBy',
        ),
        migrations.RemoveField(
            model_name='ordermaster',
            name='createdBy',
        ),
        migrations.RemoveField(
            model_name='ordermaster',
            name='custID',
        ),
        migrations.RemoveField(
            model_name='ordermaster',
            name='paymentID',
        ),
        migrations.RemoveField(
            model_name='ordermaster',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ordermaster',
            name='updatedBy',
        ),
        migrations.RemoveField(
            model_name='sstemplates',
            name='createdBy',
        ),
        migrations.RemoveField(
            model_name='sstemplates',
            name='css',
        ),
        migrations.RemoveField(
            model_name='sstemplates',
            name='html',
        ),
        migrations.RemoveField(
            model_name='sstemplates',
            name='templateType',
        ),
        migrations.RemoveField(
            model_name='sstemplates',
            name='updatedBy',
        ),
        migrations.AddField(
            model_name='custmaster',
            name='last_name',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='custmaster',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 780942)),
        ),
        migrations.AlterField(
            model_name='custmaster',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 780980)),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 787919)),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 787950)),
        ),
        migrations.AlterField(
            model_name='sstemplates',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 781681)),
        ),
        migrations.AlterField(
            model_name='sstemplates',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 5, 14, 57, 781712)),
        ),
    ]
