# Generated by Django 2.1 on 2021-01-21 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0005_auto_20210111_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='userExports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.IntegerField(blank=True, default=0)),
                ('site_name', models.CharField(max_length=250)),
                ('platform', models.CharField(max_length=250)),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 192683))),
                ('updatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 192718))),
            ],
            options={
                'db_table': 'user_exports',
            },
        ),
        migrations.AddField(
            model_name='sssubscriptionplansdetails',
            name='total_export_credits',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='sssubscriptionplansdetails',
            name='total_sites',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='userbackupsettings',
            name='user_site_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='userfontssettings',
            name='user_site_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='userformssettings',
            name='user_site_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='usergeneralsettings',
            name='sub_domain',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AddField(
            model_name='usergeneralsettings',
            name='user_site_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='userseosettings',
            name='user_site_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='custmaster',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 174042)),
        ),
        migrations.AlterField(
            model_name='custmaster',
            name='cust_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='custmaster',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 174081)),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 182388)),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 182421)),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 181659)),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='cust_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order_master_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 181689)),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 180992)),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='cust_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 181023)),
        ),
        migrations.AlterField(
            model_name='sslatestoffers',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 190972)),
        ),
        migrations.AlterField(
            model_name='sslatestoffers',
            name='endDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 190935)),
        ),
        migrations.AlterField(
            model_name='sslatestoffers',
            name='isActive',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='sslatestoffers',
            name='startDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 190894)),
        ),
        migrations.AlterField(
            model_name='sslatestoffers',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 190991)),
        ),
        migrations.AlterField(
            model_name='ssroadmapreleases',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 191858)),
        ),
        migrations.AlterField(
            model_name='ssroadmapreleases',
            name='isActive',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ssroadmapreleases',
            name='releaseDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 191781)),
        ),
        migrations.AlterField(
            model_name='ssroadmapreleases',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 191905)),
        ),
        migrations.AlterField(
            model_name='sssubscriptionplans',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 176462)),
        ),
        migrations.AlterField(
            model_name='sssubscriptionplans',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 176645)),
        ),
        migrations.AlterField(
            model_name='sssubscriptionplansdetails',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 179500)),
        ),
        migrations.AlterField(
            model_name='sssubscriptionplansdetails',
            name='is_active',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='sssubscriptionplansdetails',
            name='ss_subscription_plans_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='sssubscriptionplansdetails',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 179530)),
        ),
        migrations.AlterField(
            model_name='sstemplates',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 175122)),
        ),
        migrations.AlterField(
            model_name='sstemplates',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 175154)),
        ),
        migrations.AlterField(
            model_name='sswebsitetype',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 175809)),
        ),
        migrations.AlterField(
            model_name='sswebsitetype',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 175841)),
        ),
        migrations.AlterField(
            model_name='userbackupsettings',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 190079)),
        ),
        migrations.AlterField(
            model_name='userbackupsettings',
            name='cust_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userbackupsettings',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 190112)),
        ),
        migrations.AlterField(
            model_name='userbillingaddress',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 180231)),
        ),
        migrations.AlterField(
            model_name='userbillingaddress',
            name='cust_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userbillingaddress',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 180261)),
        ),
        migrations.AlterField(
            model_name='userdomain',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 183792)),
        ),
        migrations.AlterField(
            model_name='userdomain',
            name='cust_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userdomain',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 183822)),
        ),
        migrations.AlterField(
            model_name='userdomainhost',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 184534)),
        ),
        migrations.AlterField(
            model_name='userdomainhost',
            name='cust_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userdomainhost',
            name='domain_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userdomainhost',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 184563)),
        ),
        migrations.AlterField(
            model_name='userfontssettings',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 189291)),
        ),
        migrations.AlterField(
            model_name='userfontssettings',
            name='cust_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userfontssettings',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 189334)),
        ),
        migrations.AlterField(
            model_name='userformssettings',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 188496)),
        ),
        migrations.AlterField(
            model_name='userformssettings',
            name='cust_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userformssettings',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 188526)),
        ),
        migrations.AlterField(
            model_name='usergeneralsettings',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 186909)),
        ),
        migrations.AlterField(
            model_name='usergeneralsettings',
            name='cust_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usergeneralsettings',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 186939)),
        ),
        migrations.AlterField(
            model_name='usernotificationsettings',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 183033)),
        ),
        migrations.AlterField(
            model_name='usernotificationsettings',
            name='cust_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usernotificationsettings',
            name='notifications_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usernotificationsettings',
            name='setting',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usernotificationsettings',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 183064)),
        ),
        migrations.AlterField(
            model_name='userpaymentmethod',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 177333)),
        ),
        migrations.AlterField(
            model_name='userpaymentmethod',
            name='cust_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userpaymentmethod',
            name='stripe_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userpaymentmethod',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 177363)),
        ),
        migrations.AlterField(
            model_name='userseosettings',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 187774)),
        ),
        migrations.AlterField(
            model_name='userseosettings',
            name='cust_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userseosettings',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 187806)),
        ),
        migrations.AlterField(
            model_name='usersites',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 178034)),
        ),
        migrations.AlterField(
            model_name='usersites',
            name='cust_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usersites',
            name='site_website_type_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usersites',
            name='template_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usersites',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 178063)),
        ),
        migrations.AlterField(
            model_name='usersitesplan',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 178728)),
        ),
        migrations.AlterField(
            model_name='usersitesplan',
            name='cust_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usersitesplan',
            name='is_active',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usersitesplan',
            name='subscription_plan_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usersitesplan',
            name='updatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 8, 11, 17, 178755)),
        ),
        migrations.AlterField(
            model_name='usersitesplan',
            name='user_site_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
